/**
 * This file was generated by the JPA Modeler
 */
package com.j2mk.israelgo.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity
@Table(name = "oferta")
public class Oferta implements Serializable {

    @Column(name = "ofer_id", unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "ofer_porcentaje")
    @Basic
    private Double porcentaje;

    @Column(name = "ofer_valor_separacion")
    @Basic
    private Double valorSeparacion;

    @Column(name = "ofer_nombre", unique = true)
    @Basic
    private String nombre;

    @Column(name = "ofer_numero_cuotas")
    @Basic
    private String numeroCuotas;

    @Column(name = "ofer_periodicidad")
    @Basic
    private String periodicidad;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getPorcentaje() {
        return this.porcentaje;
    }

    public void setPorcentaje(Double porcentaje) {
        this.porcentaje = porcentaje;
    }

    public Double getValorSeparacion() {
        return this.valorSeparacion;
    }

    public void setValorSeparacion(Double valorSeparacion) {
        this.valorSeparacion = valorSeparacion;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getNumeroCuotas() {
        return this.numeroCuotas;
    }

    public void setNumeroCuotas(String numeroCuotas) {
        this.numeroCuotas = numeroCuotas;
    }

    public String getPeriodicidad() {
        return this.periodicidad;
    }

    public void setPeriodicidad(String periodicidad) {
        this.periodicidad = periodicidad;
    }

}
