/**
 * This file was generated by the JPA Modeler
 */
package com.j2mk.israelgo.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * @author jdmp
 */
@Entity
@Table(name = "proyecto")
@NamedQuery(name = "Proyecto.findByEmpresa", query = "Select p from Proyecto p WHERE p.empresa.id = :empresa_id")
public class Proyecto implements Serializable {

    @Column(name = "proyecto_id", unique = true)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "proyecto_nombre", unique = true)
    @Basic
    private String nombre;

    @ManyToOne(targetEntity = PlanPago.class)
    @JoinColumn(name = "PLANPAGO_ID")
    private PlanPago planPago;

    @ManyToOne(targetEntity = Empresa.class)
    @JoinColumn(name = "EMPRESA_ID")
    private Empresa empresa;

    @ManyToOne(targetEntity = Oferta.class)
    @JoinColumn(name = "OFERTA_ID")
    private Oferta oferta;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public PlanPago getPlanPago() {
        return this.planPago;
    }

    public void setPlanPago(PlanPago planPago) {
        this.planPago = planPago;
    }

    public Empresa getEmpresa() {
        return this.empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public Oferta getOferta() {
        return this.oferta;
    }

    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }

}
